### ISSUE TITLE
AssertionError: could not determine account from provided accessToken

### ISSUE THREAD

**Issue by mushon** [mapbox/framer-example#5]
Framer requires an update and then complains about invalid indentations. After fixing the mixed of space and tab indentations I still get ``AssertionError: could not determine account from provided accessToken`` which prevents the prototype from running.

**Comment by mayagao** [comment]
Hi,

I just updated the README https://github.com/mapbox/framer-example#explore-examples- and added a simple map view example https://github.com/mapbox/framer-example/tree/master/simple-map-view. This should work in Framer v93
