### ISSUE TITLE
Update dataset example to the latest framer version

### ISSUE THREAD

**Issue by mayagao** [mapbox/framer-example#6]

**Comment by alelordelo** [comment]
Hi Maya! Any news on the dataset example for latest Framer?

I tried the code bellow but didn't work...

mapboxClient = new mapboxgl(mapboxgl.accessToken)


Help me please! ; )

best

**Comment by mayagao** [comment]
Hi Alexandre, Sorry for the late response. I am no longer working on/maintaining this repo anymore. You will need to replace `mapboxgl.accessToken` with your own mapbox access token. I suggest you following the steps listed here https://github.com/mapbox/framer-example#basic-set-up- to set up a basic map.
